#%RAML 1.0 DataType
properties:
  id: number
  name: string
  city: string
  country: string
  iataCode: string
  icaoCode: string
  latitude: string
  longitude: string
  altitude: string
  timeZone: string
  dst: string
  tzTimeZone: string
  type: string
  source: string
