#%RAML 1.0 DataType

properties:
  airline?: string
  airlineId: number
  sourceAirport?: string
  sourceAirportId: number
  destinationAirport?: string
  destinationAirportId: number
  codeShare?: string
  stops?: boolean
  equipment?: string